//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entellication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Call
    {
        public int CallID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> TechnicianID { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<int> ReferenceNumber { get; set; }
        public string Status { get; set; }
        public Nullable<int> ProductID { get; set; }
    }
}
